library(quantmod)
library(xts)
library(stringr)
library(forcats)
library(lubridate)
library(dplyr)
#Below are the companies, which have made public pledges
getSymbols("AMZN",from="2020-05-25",to="2020-06-10")
AMZN_log_returns<-AMZN%>%Ad()%>%dailyReturn(type='log')
AMZN%>%Ad()%>%chartSeries(data,name="Amazon")
getSymbols("UNH",from="2020-05-25",to="2020-06-10")
UNH_log_returns<-UNH%>%Ad()%>%dailyReturn(type='log')
UNH%>%Ad()%>%chartSeries(data,name="United Healthcare")
getSymbols("CMCSA",from="2020-05-25",to="2020-06-10")
CMCSA_log_returns<-CMCSA%>%Ad()%>%dailyReturn(type='log')
CMCSA%>%Ad()%>%chartSeries(data,name="Comcast")
getSymbols("VZ",from="2020-05-25",to="2020-06-10")
VZ_log_returns<-VZ%>%Ad()%>%dailyReturn(type='log')
VZ%>%Ad()%>%chartSeries(data,name="Verizon")
getSymbols("FB",from="2020-05-25",to="2020-06-10")
FB_log_returns<-FB%>%Ad()%>%dailyReturn(type='log')
FB%>%Ad()%>%chartSeries(data,name="Facebook")
getSymbols("LULU",from="2020-05-25",to="2020-06-10")
LULU_log_returns<-LULU%>%Ad()%>%dailyReturn(type='log')
LULU%>%Ad()%>%chartSeries(data,name="Lululemon")
getSymbols("BAC",from="2020-05-25",to="2020-06-10")
BAC_log_returns<-BAC%>%Ad()%>%dailyReturn(type='log')
BAC%>%Ad()%>%chartSeries(data,name="Bank of America")
getSymbols("DIS",from="2020-05-25",to="2020-06-10")
DIS_log_returns<-DIS%>%Ad()%>%dailyReturn(type='log')
DIS%>%Ad()%>%chartSeries(data,name="Disney")
getSymbols("PG",from="2020-05-25",to="2020-06-10")
PG_log_returns<-PG%>%Ad()%>%dailyReturn(type='log')
PG%>%Ad()%>%chartSeries(data,name="Proctor & Gamble")
getSymbols("LYFT",from="2020-05-25",to="2020-06-10")
LYFT_log_returns<-LYFT%>%Ad()%>%dailyReturn(type='log')
LYFT%>%Ad()%>%chartSeries(data,name="Lyft")
getSymbols("NTDOY",from="2020-05-25",to="2020-06-10")
NTDOY_log_returns<-NTDOY%>%Ad()%>%dailyReturn(type='log')
NTDOY%>%Ad()%>%chartSeries(data,name="Nintendo")
getSymbols("EA",from="2020-05-25",to="2020-06-10")
EA_log_returns<-EA%>%Ad()%>%dailyReturn(type='log')
EA%>%Ad()%>%chartSeries(data,name="Electronic Arts")
getSymbols("MCD",from="2020-05-25",to="2020-06-10")
MCD_log_returns<-MCD%>%Ad()%>%dailyReturn(type='log')
MCD%>%Ad()%>%chartSeries(data,name="McDonald's")
getSymbols("AAPL",from="2020-05-25",to="2020-06-10")
AAPL_log_returns<-AAPL%>%Ad()%>%dailyReturn(type='log')
AAPL%>%Ad()%>%chartSeries(data,name="Apple")
getSymbols("WORK",from="2020-05-25",to="2020-06-10")
WORK_log_returns<-WORK%>%Ad()%>%dailyReturn(type='log')
WORK%>%Ad()%>%chartSeries(data,name="Slack")
getSymbols("AWAY",from="2020-05-25",to="2020-06-10")
AWAY_log_returns<-AWAY%>%Ad()%>%dailyReturn(type='log')
AWAY%>%Ad()%>%chartSeries(data,name="Away")
getSymbols("UBER",from="2020-05-25",to="2020-06-10")
UBER_log_returns<-UBER%>%Ad()%>%dailyReturn(type='log')
UBER%>%Ad()%>%chartSeries(data,name="Uber")
getSymbols("CSCO",from="2020-05-25",to="2020-06-10")
CSCO_log_returns<-CSCO%>%Ad()%>%dailyReturn(type='log')
CSCO%>%Ad()%>%chartSeries(data,name="Cisco")
getSymbols("INTC",from="2020-05-25",to="2020-06-10")
INTC_log_returns<-INTC%>%Ad()%>%dailyReturn(type='log')
INTC%>%Ad()%>%chartSeries(data,name="Intel")
getSymbols("SHOP",from="2020-05-25",to="2020-06-10")
SHOP_log_returns<-SHOP%>%Ad()%>%dailyReturn(type='log')
SHOP%>%Ad()%>%chartSeries(data,name="Shopify")
getSymbols("GPS",from="2020-05-25",to="2020-06-10")
GPS_log_returns<-GPS%>%Ad()%>%dailyReturn(type='log')
GPS%>%Ad()%>%chartSeries(data,name="Gap Inc.")
getSymbols("ETSY",from="2020-05-25",to="2020-06-10")
ETSY_log_returns<-ETSY%>%Ad()%>%dailyReturn(type='log')
ETSY%>%Ad()%>%chartSeries(data,name="Etsy")
getSymbols("LVMUY",from="2020-05-25",to="2020-06-10")
LVMUY_log_returns<-LVMUY%>%Ad()%>%dailyReturn(type='log')
LVMUY%>%Ad()%>%chartSeries(data,name="Louis Vuitton Moet Hennessy")
getSymbols("SEQUX",from="2020-05-25",to="2020-06-10")
SEQUX_log_returns<-SEQUX%>%Ad()%>%dailyReturn(type='log')
SEQUX%>%Ad()%>%chartSeries(data,name="Sequoia Capital")
getSymbols("PTON",from="2020-05-25",to="2020-06-10")
PTON_log_returns<-PTON%>%Ad()%>%dailyReturn(type='log')
PTON%>%Ad()%>%chartSeries(data,name="Peloton")
getSymbols("GOOGL",from="2020-05-25",to="2020-06-10")
GOOGL_log_returns<-GOOGL%>%Ad()%>%dailyReturn(type='log')
GOOGL%>%Ad()%>%chartSeries(data,name="Alphabet")
getSymbols("LOW",from="2020-05-25",to="2020-06-10")
LOW_log_returns<-LOW%>%Ad()%>%dailyReturn(type='log')
LOW%>%Ad()%>%chartSeries(data,name="Loews")


#Below are the brands who have made public statements
getSymbols("NKE",from="2020-05-25",to="2020-06-10")
NKE_log_returns<-NKE%>%Ad()%>%dailyReturn(type='log')
NKE%>%Ad()%>%chartSeries(data,name="Nike")
getSymbols("TWTR",from="2020-05-25",to="2020-06-10")
TWTR_log_returns<-TWTR%>%Ad()%>%dailyReturn(type='log')
TWTR%>%Ad()%>%chartSeries(data,name="Twitter")
getSymbols("YUM",from="2020-05-25",to="2020-06-10")
YUM_log_returns<-YUM%>%Ad()%>%dailyReturn(type='log')
YUM%>%Ad()%>%chartSeries(data,name="Yum! Brands")
getSymbols("GM",from="2020-05-25",to="2020-06-10")
GM_log_returns<-GM%>%Ad()%>%dailyReturn(type='log')
GM%>%Ad()%>%chartSeries(data,name="General Motors")
getSymbols("SBUX",from="2020-05-25",to="2020-06-10")
SBUX_log_returns<-SBUX%>%Ad()%>%dailyReturn(type='log')
SBUX%>%Ad()%>%chartSeries(data,name="Starbucks")
getSymbols("SNE",from="2020-05-25",to="2020-06-10")
SNE_log_returns<-SNE%>%Ad()%>%dailyReturn(type='log')
SNE%>%Ad()%>%chartSeries(data,name="Sony")
getSymbols("SNAP",from="2020-05-25",to="2020-06-10")
SNAP_log_returns<-SNAP%>%Ad()%>%dailyReturn(type='log')
SNAP%>%Ad()%>%chartSeries(data,name="SnapChat")
getSymbols("BLK",from="2020-05-25",to="2020-06-10")
BLK_log_returns<-BLK%>%Ad()%>%dailyReturn(type='log')
BLK%>%Ad()%>%chartSeries(data,name="BlackRock")
getSymbols("MSFT",from="2020-05-25",to="2020-06-10")
MSFT_log_returns<-MSFT%>%Ad()%>%dailyReturn(type='log')
MSFT%>%Ad()%>%chartSeries(data,name="Microsoft")

